{
 "title": "Solana Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(solana_active_validators, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "validator desync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_last_vote - on(service) group_left() max by(env, service) (solana_validator_last_vote{service=~\"$service\"}) > -500000"
    }
   ]
  },
  {
   "title": "rate(max(last_voted))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(max by(env, service) (solana_validator_last_vote{service=~\"$service\"})[1m:])"
    }
   ]
  },
  {
   "title": "active / delinquent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_active_validators{service=~\"$service\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "max(root_slot)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_root_slot{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "max(last_voted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_last_vote{service=~\"$service\"})"
    }
   ]
  }
 ]
}